---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: '`arboles["height"].quantile(0.95)` es lo mismo que  `arboles["height"].max()`'
  checked: false
- value: '`arboles["height"].quantile(1)` es lo mismo que  `arboles["height"].min()`'
  checked: false
- value: '`arboles["height"].quantile(0)` es lo mismo que  `arboles["height"].min()`'
  checked: true
- value: '`arboles["height"].quantile(0.75)` es lo mismo que  `arboles["height"].median()`'
  checked: false
- value: '`arboles["height"].quantile(1)` es lo mismo que  `arboles["height"].max()`'
  checked: true
- value: '`arboles["height"].quantile(0.5)` es lo mismo que  `arboles["height"].median()`'
  checked: true
name: Todo en-caja
