---
locale: es
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: '`min(arboles["height"])`'
  checked: true
- value: "`min([2, 4, 8, 16, 32, 64, 128, 256, 512, 1024])`"
  checked: true
- value: '`sum(arboles["diameter"])`'
  checked: true
- value: "`sum([2, 4, 8, 16, 32, 64, 128, 256, 512, 1024])`"
  checked: true
- value: '`mean(arboles["inclination"])`'
  checked: false
- value: "`mean([2, 4, 8, 16, 32, 64, 128, 256, 512, 1024])`"
  checked: false
goal: |
  --- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_output_includes
  output: 'NameError: name ''mean'' is not defined'
name: "¿Disponible sólo en series?"
